### ISSUE TITLE
Compatability Zimbra 8.6

### ISSUE THREAD

**Issue by mnlservices** [EmailConsortium/alfresco-zimlet#4]
Hi, 
I installed the zimlet on Zimbra 8.6 together with Alfresco 5.0d
I can authenticate, but when I open zimbra in my browser I get an error and it doesn't work.
I get the following error:

"TypeError: Object doesn't support property or method 'getTabView' "

I am very eager to use this great tool, but keep on running in this error.
Can you help me on this?

Kind regards,
Dick

**Comment by tuanta** [comment]
The current version of this zimlet supports Zimbra 7.x and Alfresco 4.x only.
We have no specific plan to upgrade it because of lack of resources. I do hope it would be changed in the future.
Keep in touch please.

**Comment by mnlservices** [comment]
Hi,
Thanks for you quick reply.
I hope it will be soon :-)

Thanks in advance.

Dick

On Thu, Jul 9, 2015 at 10:44 AM, Truong Anh Tuan notifications@github.com
wrote:

> Closed #4 https://github.com/EmailConsortium/alfresco-zimlet/issues/4.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/EmailConsortium/alfresco-zimlet/issues/4#event-351637513
> .

## 

_Dick Muller_
_Senior Technical Architect_

[image: HintTech]  http://www.hinttech.com/
Mastering the value of content
creative | technology | content

Delftechpark 37i
2628 XJ Delft
The Netherlands
T: +31 88 268 25 00
M: +31 6 4647 7690

[image: http://www.hinttech.com] http://www.hinttech.com/
https://twitter.com/HintTech  http://www.facebook.com/HintTech
http://www.linkedin.com/company/hinttech
https://plus.google.com/+HintTechBV
